#Build stage
FROM node:20.18-alpine AS build

WORKDIR /app

COPY package*.json .

RUN npm install

RUN apk add openssl

COPY . .

RUN npm run build

#Production stage
FROM node:20.18-alpine AS production

WORKDIR /app

COPY package*.json .

RUN npm ci --only=production

COPY --from=build /app/dist ./dist

CMD ["node", "dist/src/index.js"]