export const states = [
  "Andaman and Nicobar Islands",
  "Andhra Pradesh",
  "Arunachal Pradesh",
  "Assam",
  "Bihar",
  "Chandigarh",
  "Chhattisgarh",
  "Dadra and Nagar Haveli",
  "Daman and Diu",
  "Delhi",
  "Goa",
  "Gujarat",
  "Haryana",
  "Himachal Pradesh",
  "Jammu and Kashmir",
  "Jharkhand",
  "Karnataka",
  "Kerala",
  "Lakshadweep",
  "Madhya Pradesh",
  "Maharashtra",
  "Manipur",
  "Meghalaya",
  "Mizoram",
  "Nagaland",
  "Odisha",
  "Puducherry",
  "Punjab",
  "Rajasthan",
  "Sikkim",
  "Tamil Nadu",
  "Telangana",
  "Tripura",
  "Uttar Pradesh",
  "Uttarakhand",
  "West Bengal",
] as const;

export const cities = [
  "Ahmedabad",
  "Anand",
  "Bandra",
  "Barabanki",
  "Bareilly",
  "Bhiwandi",
  "Bhopal",
  "Bhubaneswar",
  "Budaun",
  "Chandrapur",
  "Chittorgarh",
  "Dahod",
  "Darbhanga",
  "Dehradun",
  "Dhule",
  "Durg",
  "East Champaran",
  "Faridabad",
  "Fatehpur",
  "Gaya",
  "Ghaziabad",
  "Godhra",
  "Guwahati",
  "Hardoi",
  "Hisar",
  "Hoshangabad",
  "Indore",
  "Jabalpur",
  "Jaipur",
  "Jaisalmer",
  "Jhansi",
  "Jodhpur",
  "Kadapa",
  "Kalyan",
  "Kandla",
  "Kanpur",
] as const;
